# Joint limits for ABB YuMi robot
# Apenas velocidade e aceleração — limites de posição vêm do URDF
joint_limits:
  yumi_joint_1_l:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 3.0
  yumi_joint_2_l:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 3.0
  yumi_joint_7_l:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 3.0
  yumi_joint_3_l:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 3.0
  yumi_joint_4_l:
    has_velocity_limits: true
    max_velocity: 6.9813
    has_acceleration_limits: true
    max_acceleration: 6.0
  yumi_joint_5_l:
    has_velocity_limits: true
    max_velocity: 6.9813
    has_acceleration_limits: true
    max_acceleration: 6.0
  yumi_joint_6_l:
    has_velocity_limits: true
    max_velocity: 6.9813
    has_acceleration_limits: true
    max_acceleration: 6.0
  yumi_joint_1_r:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 3.0
  yumi_joint_2_r:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 3.0
  yumi_joint_7_r:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 3.0
  yumi_joint_3_r:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 3.0
  yumi_joint_4_r:
    has_velocity_limits: true
    max_velocity: 6.9813
    has_acceleration_limits: true
    max_acceleration: 6.0
  yumi_joint_5_r:
    has_velocity_limits: true
    max_velocity: 6.9813
    has_acceleration_limits: true
    max_acceleration: 6.0
  yumi_joint_6_r:
    has_velocity_limits: true
    max_velocity: 6.9813
    has_acceleration_limits: true
    max_acceleration: 6.0
  gripper_l_joint:
    has_velocity_limits: true
    max_velocity: 0.025
    has_acceleration_limits: true
    max_acceleration: 0.1
  gripper_r_joint:
    has_velocity_limits: true
    max_velocity: 0.025
    has_acceleration_limits: true
    max_acceleration: 0.1
