planning_plugins:
  - ompl_interface/OMPLPlanner
request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/DisplayMotionPath

planner_configs:
  SBLkConfigDefault:
    type: geometric::SBL
    range: 0.0
  ESTkConfigDefault:
    type: geometric::EST
    range: 0.0
    goal_bias: 0.05
  RRTkConfigDefault:
    type: geometric::RRT
    range: 0.0
    goal_bias: 0.05
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: 1
  TRRTkConfigDefault:
    type: geometric::TRRT
    range: 0.0
    goal_bias: 0.05
    max_states_failed: 10
    temp_change_factor: 2.0
    min_temperature: 10e-10
    init_temperature: 10e-6
    frountier_threshold: 0.0
    frountierNodeRatio: 0.1
    k_constant: 0.0
  PRMkConfigDefault:
    type: geometric::PRM
    max_nearest_neighbors: 10
  PRMstarkConfigDefault:
    type: geometric::PRMstar

left_arm:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(yumi_joint_1_l,yumi_joint_2_l,yumi_joint_7_l)
  longest_valid_segment_fraction: 0.005

right_arm:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(yumi_joint_1_r,yumi_joint_2_r,yumi_joint_7_r)
  longest_valid_segment_fraction: 0.005

both_arms:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(yumi_joint_1_l,yumi_joint_2_l,yumi_joint_1_r,yumi_joint_2_r)
  longest_valid_segment_fraction: 0.005
